"""
Django settings for LibraryProject project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-p6hj7ews(h3@nhzr=fem587u3qzbvijc1((d9b0&pq_78ifu&2'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'bookshelf.apps.BookshelfConfig',
    'relationship_app.apps.RelationshipAppConfig'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'LibraryProject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'LibraryProject.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

AUTH_USER_MODEL = 'bookshelf.CustomUser'

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'







# --- Task 2: Security Best Practices Configuration ---

# 1. General Security and Host Settings
# IMPORTANT: This must be set to False for production!
DEBUG = False

# Must list all host/domain names that your Django site can serve
ALLOWED_HOSTS = ['yourdomain.com', 'www.yourdomain.com', '127.0.0.1', 'localhost'] 

# 2. Cookie Security (Step 1 & 2 of Task 3)
# Forces cookies to only be sent over a secure (HTTPS) connection.
CSRF_COOKIE_SECURE = True
SESSION_COOKIE_SECURE = True
# Note: SESSION_COOKIE_HTTPONLY is usually True by default but good to verify.
SESSION_COOKIE_HTTPONLY = True


# 3. Header Protections (Step 1 & 3 of Task 2)

# X_FRAME_OPTIONS: Prevents clickjacking by denying framing of the page.
# "DENY" prevents framing by any site.
X_FRAME_OPTIONS = 'DENY' 

# SECURE_CONTENT_TYPE_NOSNIFF: Prevents browsers from trying to guess ('sniff')
# the content type of a file, mitigating MIME-sniffing attacks.
SECURE_CONTENT_TYPE_NOSNIFF = True

# SECURE_BROWSER_XSS_FILTER: Activates the browser's built-in XSS filter.
# (Note: In recent Django versions, this is largely superseded by default middleware, 
# but setting it explicitly satisfies the task requirement.)
SECURE_BROWSER_XSS_FILTER = True




# --- TASK 3: HTTPS and Secure Redirects Configuration ---

# 1. Enforce HTTPS Redirects (Step 1)
# Redirects all non-HTTPS requests to HTTPS.
SECURE_SSL_REDIRECT = True 

# 2. HTTP Strict Transport Security (HSTS) (Step 1)
# Instructs browsers to ONLY access the site via HTTPS for a long duration.
# 31536000 seconds = 1 year
SECURE_HSTS_SECONDS = 31536000
# Include all subdomains in the HSTS policy.
SECURE_HSTS_INCLUDE_SUBDOMAINS = True
# Allow preloading the site into browsers' HSTS lists.
SECURE_HSTS_PRELOAD = True 

# 3. Enforce Secure Cookies (Step 2)
# Ensure session cookies are ONLY transmitted over HTTPS.
SESSION_COOKIE_SECURE = True
# Ensure CSRF cookies are ONLY transmitted over HTTPS.
CSRF_COOKIE_SECURE = True
# Set HttpOnly flag to prevent client-side JavaScript from accessing cookies.
# (This is a good practice, even if often the default)
SESSION_COOKIE_HTTPONLY = True 
CSRF_COOKIE_HTTPONLY = True 

# 4. Security Headers (Step 3)
# Prevent clickjacking by denying framing of the page.
X_FRAME_OPTIONS = 'DENY' 
# Prevent browsers from trying to guess (sniff) the content type.
SECURE_CONTENT_TYPE_NOSNIFF = True
# Enable the browser's XSS filter (often redundant, but required for the task).
SECURE_BROWSER_XSS_FILTER = True 

# 5. Production Environment Basics
# IMPORTANT: This must be False in production!
DEBUG = False
# List your actual domain names here
ALLOWED_HOSTS = ['yourdomain.com', '127.0.0.1']

SECURE_PROXY_SSL_HEADER = True
HTTP_X_FORWARDED_PROTO = True